### ISSUE TITLE
FIX (Navbox 2 col) Remove half-box when only one item is entered

### ISSUE THREAD

**Issue by garethjmsaunders** [standrewsdigital/digital-pattern-library#6]
## Need to merge the navbox branch to make this fix go live

When using the digital transformation content item Navbox (2 col), there is a bug if you only add one piece of content. This manifests as a box half appearing on the page as can be seen here - http://www.st-andrews.ac.uk/students/advice/personal/sexual-misconduct/

Could someone please fix this bug so that if only one piece of information is entered, the second box does not appear?

Sexual misconduct page cannot go live without this.

---

Responsible: Aaron
Tester:

**Comment by garethjmsaunders** [comment]
Aaron: We can use the psuedo selector and do this in CSS:

```
.navbox-title:empty {
display: none;
}
```

Confirmed, this will be fixed when the changes are pushed to the pattern library.

**Comment by Aarontlott** [comment]
I think this bug is fixed in the aaron-navbox branch, super simple fix. I'll submit a pull request.

**Comment by Aarontlott** [comment]
Unfortunately not a simple fix, the CSS :empty class is very particular about when it equates to actually empty. Needs to be programmed into the particular method, i.e. terminalFOUR or otherwise, to not build ones that are empty. Otherwise if needed we can hide the last one or two, but without knowing how it's built it's impossible to build for that long term.

**Comment by Aarontlott** [comment]
Decided upon making sure we build in an ability to hide/not-use the 2nd box if needed in whichever platform we build this in. In T4 this was adjusting the content type to hide empty fields if needed. Could be a dropdown or otherwise. In the future of T4 this could be much easier with programmable layouts.
